const ActionMasterType = {
    // GET_USER: 'GET_USER',
    // GET_USER_SUCCEED: 'GET_USER_SUCCEED',
    // GET_USER_FAILED: 'GET_USER_FAILED',
    //  ============= REGIONS ================ //
    GET_REGIONS: 'GET_REGIONS',
    GET_REGIONS_SUCCEED: 'GET_REGIONS_SUCCEED',
    GET_REGIONS_FAILED: 'GET_REGIONS_FAILED',
    ADD_REGIONS: 'ADD_REGIONS',
    ADD_REGIONS_SUCCEED: 'ADD_REGIONS_SUCCEED',
    ADD_REGIONS_FAILED: 'ADD_REGIONS_FAILED',
    UPDATE_REGIONS: 'UPDATE_REGIONS',
    UPDATE_REGIONS_SUCCEED: 'UPDATE_REGIONS_SUCCEED',
    UPDATE_REGIONS_FAILED: 'UPDATE_REGIONS_FAILED',
    DEL_REGIONS: 'DEL_REGIONS',
    DEL_REGIONS_SUCCEED: 'DEL_REGIONS_SUCCEED',
    DEL_REGIONS_FAILED: 'DEL_REGIONS_FAILED',
    
    // ============= Country ============ //
    GET_COUNTRY: 'GET_COUNTRY',
    GET_COUNTRY_SUCCEED: 'GET_COUNTRY_SUCCEED',
    GET_COUNTRY_FAILED: 'GET_COUNTRY_FAILED',
    ADD_COUNTRY: 'ADD_COUNTRY',
    ADD_COUNTRY_SUCCEED: 'ADD_COUNTRY_SUCCEED',
    ADD_COUNTRY_FAILED: 'ADD_COUNTRY_FAILED',
    UPDATE_COUNTRY: 'UPDATE_COUNTRY',
    UPDATE_COUNTRY_SUCCEED: 'UPDATE_COUNTRY_SUCCEED',
    UPDATE_COUNTRY_FAILED: 'UPDATE_COUNTRY_FAILED',
    DEL_COUNTRY: 'DEL_COUNTRY',
    DEL_COUNTRY_SUCCEED: 'DEL_COUNTRY_SUCCEED',
    DEL_COUNTRY_FAILED: 'DEL_COUNTRY_FAILED'
}

export default ActionMasterType;
